acounts/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path,include
from .forms import UserLoginForm
from .views import RegisterView,edit_profile

urlpatterns = [
    path('login/', LoginView.as_view(authentication_form=UserLoginForm), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', edit_profile, name='profile'),
    path('', include('django.contrib.auth.urls')),

]

project/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.ProjectView.as_view(),name='view' ),
    path('create',views.ProjectCreate.as_view(),name='create' ),
    path('project/update/<int:pk>',views.ProjectUpdateView.as_view(), name='project_update'),
    path('task/create', views.TaskCreateView.as_view(), name='task_create'),
    path('task/update/<int:pk>', views.TaskUpdateView.as_view(), name='task_update'),
    path('task/delete/<int:pk>', views.TaskDeleteView.as_view(), name='task_delete'),
    path('project/delete/<int:pk>', views.ProjectDeleteView.as_view(), name='project_delete'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path,include
from project import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(urls)),
    path('accounts/',include('acounts.urls'))
]

acounts/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models
from django.conf.global_settings import AUTH_USER_MODEL
# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=255)

    def __str__(self):
        return self.name
class num_task(models.IntegerChoices):
    PANDING=1,'panding'
    COMPLETE=2,'complete'
    POSTPONED=3,'postponed'
    CANCEL=4,'cancel'

class Progect(models.Model):
    title=models.CharField(max_length=255)
    description=models.TextField()
    statues = models.IntegerField(choices=num_task.choices,default=num_task.PANDING)
    create_at=models.DateTimeField(auto_now_add=True)
    updata_at=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(category,on_delete=models.PROTECT)
    user=models.ForeignKey(AUTH_USER_MODEL,on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class task(models.Model):

    description = models.TextField()
    is_complete = models.BooleanField(default=False)
    project = models.ForeignKey(Progect,on_delete=models.CASCADE)

    def __str__(self):
        return self.description

acounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm,UserChangeForm,UserCreationForm
from django.contrib.auth.models import User
attrs={'class': 'form-control'}


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(attrs=attrs),

    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs=attrs),
    )



class UserRegisterForm(UserCreationForm):

    first_name = forms.CharField(label='First Name', widget=forms.TextInput(attrs=attrs))

    last_name = forms.CharField(label='Last Name', widget=forms.TextInput(attrs=attrs))

    username = forms.CharField( label='Username', widget=forms.TextInput(attrs=attrs),)

    email = forms.EmailField(label='Email',widget=forms.TextInput(attrs=attrs),)

    password1 = forms.CharField(label='Password',widget=forms.PasswordInput(attrs=attrs),)

    password2 = forms.CharField(label='Password Confirm',widget=forms.PasswordInput(attrs=attrs),)


    class Meta(UserCreationForm.Meta):
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')




class ProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'username': forms.EmailInput(attrs={'class': 'form-control'}),
        }

project/forms.py
from django import forms
from .models import Progect
attrs={'class': 'form-control'}
class project_forms(forms.ModelForm):

    class Meta:

        model=Progect
        fields = ['title', 'description', 'category']
        widgets= {
            'title':forms.TextInput(attrs=attrs),
            'description':forms.Textarea(attrs=attrs),
            'category':forms.Select(attrs=attrs),
        }

class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = Progect
        fields = ['title', 'description', 'category','statues']

        widgets = {
            'title': forms.TextInput(attrs=attrs),
            'description': forms.Textarea(attrs=attrs),
            'category': forms.Select(attrs=attrs),
            'statues': forms.Select(attrs=attrs),
        }

acounts/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import UserRegisterForm, ProfileForm


# Create your views here.


class RegisterView(CreateView):
    form_class = UserRegisterForm
    template_name = 'registration/register.html'

    def get_success_url(self):
        login(self.request, self.object)
        return reverse_lazy('project_list')


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')

    else:
        form = ProfileForm(instance=request.user)
        return render(request, 'profile.html', {'form': form})

project/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy,reverse
from django.views.generic import ListView,CreateView,UpdateView,DetailView,DeleteView
from .models import Progect,task,category
from .forms import project_forms,ProjectUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
class ProjectView(LoginRequiredMixin,ListView):
    model = Progect
    template_name = r'C:\Users\ali\PycharmProjects\pythonProject\pythonProject1\todo\templates\project_list.html'
    paginate_by = 2
    def get_queryset(self):
        query_set = super().get_queryset()
        where = {'user_id':self.request.user}
        q = self.request.GET.get('q', None)

        if q:
            where['title__icontains'] = q

        return query_set.filter(**where)
class ProjectCreate(LoginRequiredMixin,CreateView):
    model = Progect
    form_class = project_forms
    template_name = 'create_project.html'
    success_url = reverse_lazy('view')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


    36
class ProjectUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Progect
    form_class = ProjectUpdateForm
    template_name = 'update_project.html'

    def test_func(self):
        return self.get_object().user.id == self.request.user.id

    def get_success_url(self):
        return reverse('project_update', args=[self.object.id])



class TaskCreateView( LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model =task
    fields = ['project', 'description']
    template_name = 'create_task.html'

    def test_func(self):
        project_id = self.request.POST.get('project', '')

        return Progect.objects.get(pk=project_id).user_id == self.request.user.id
    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])



class TaskUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = task
    fields = ['is_complete']
    http_method_names = ['post']

    def test_func(self):
        return self.get_object().project.user.id == self.request.user.id
    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])






class TaskDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = task
    http_method_names = ['post']

    def test_func(self):
        return self.get_object().project.user.id == self.request.user.id
    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])



class ProjectDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Progect
    template_name = 'delete_task.html'
    success_url = reverse_lazy('view')

    def test_func(self):
        return self.get_object().user.id == self.request.user.id

acounts/templates/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
 <div class="container">
        <div class="row justify-content-md-center">
            <div class="card col-md-6 px-0">
                <div class="card-header">
                        <h3 class="mb-0 py-2"> {% trans 'profile' %}</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% include 'common/forms.html' with form=form %}
                        <button class="btn btn-success" >
                            {% trans 'profile' %}
                        </button>
                    </form>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


</head>
<body class="d-flex flex-column h-100 bg-lite">
    {% include 'base/headers.html'%}
    <main class="flex-shrink-0">
    <div class="container mt-5">
    {% block content %}
    {% endblock %}
    </div>
    </main>
     {% include 'base/footer.html'%}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

templates/base/footer.html
{% load i18n %}

<nav class="footer mt-auto py-3 bg-info border" style="    background-color: #0f4651 !important;">
  <div class="container">
    <span class="text-muted">
        {% trans '(c) 2024 Mahmoud Nasser , All rights reserved' %}
    </span>
  </div>
</nav>

templates/base/headers.html
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-dark bg-success bg-gradient p-3" style="background-color: #0f4651 !important;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'view' %}"> {% trans 'Project Management' %}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'view' %}">{% trans 'Home' %}</a>
        </li>
      </ul>
            {% if user.is_authenticated %}
           <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      {{ user.username }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'profile' %}">{% trans 'Profile' %}</a></li>
                       <li><hr class="dropdown-divider"></li>
                       <li>
                       <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="dropdown-item">{% trans 'Logout' %}</button>
                      </form>
                     </li>
                  </ul>
                </li>
           </ul>

            <form method="get" class="d-flex" action="{% url 'view' %}">
            <div class="input-group">
                <input
                        type="text"
                        name = 'q'
                        class="form-control"
                        placeholder="{% trans 'Search' %}"
                        value="{{ request.GET.q }}"
                />
                <button type="submit" class="btn btn-outline-light">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
        {% else %}
            <div>
                <a class="btn btn-outline-light" href="{% url 'login' %}">{% trans 'Login' %}</a>
            </div>
            <div>
                <a class="btn btn-outline-light" href="{% url 'register' %}">{% trans 'register' %}</a>
            </div>

        {% endif %}
   </div>

  </div>
</nav>

templates/common/forms.html
<ul>
    {% for error in form.non_field_errors %}
        <li class="list-group-item list-group-item-danger"> {{ error|escape }}</li>
    {% endfor %}

    {% for field in form %}
            {% for error in field.errors %}
                        <li class="list-group-item list-group-item-danger"> {{ error|escape }}</li>
            {% endfor %}
    {% endfor %}


</ul>





{% for field in form %}
    <div class="mb-3">
    <label class="form-label"> {{ field.label }} </label>
    {{ field }}
    </div>
{% endfor %}

templates/create_project.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}



    <div class="container">
        <div class="row justify-content-md-center">
            <div class="card col-md-6 px-0">
                <div class="card-header">
                        <h3 class="mb-0 py-2"> {% trans 'New Project' %}</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% include 'common/forms.html' with form=form %}
                        <button class="btn btn-success" >
                            {% trans 'create' %}
                        </button>
                    </form>
                </div>
            </div>

        </div>
    </div>






{% endblock %}

templates/create_task.html
{% load i18n %}

{% block content %}
    {% for task in project.task_set.all %}
        <li class="list-group-item d-flex">
            <form action="{%  url 'task_update' task.id %} " method="post" class="my-auto me-2">
                    {% csrf_token %}
                <input
                        class="form-check-input"
                        type="checkbox"
                        name="is_complete"
                        {% if task.is_complete  %}
                            checked
                        {% endif %}
                        onchange="this.form.submit()"
                />

            </form>

            <p class="my-auto me-auto">
                {{ task.description }}
            </p>

            <form action="{%  url 'task_delete' task.id %} " method="post">
                    {% csrf_token %}

                <button class="btn" type="submit" value="delete">
                    <i class="bi bi-trash text-danger"  ></i>
                </button>
            </form>

        </li>
    {% endfor %}
    </ul>

    <div class="card mt-2">
        <form method="post" class="d-flex" action="{% url 'task_create' %}">
            {% csrf_token %}
            <div class="input-group">
                <input type="hidden" value="{{ project.id }}" name="project">
                <input type="text"  name="description" placeholder="{% trans 'New Task' %} " class="form-control" required>
                <input type="submit" class="btn btn-outline-dark" value="Add Task">
            </div>

        </form>

    </div>


{% endblock %}

templates/delete_task.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h3> {% trans 'Alert' %}</h3>
    <p class="text-muted my-4">
        {% trans 'Are You Sure ? Delete Project ,  '%}
        {{ progect.title }}
    </p>

    <form action="{% url 'project_delete' progect.id %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="{% trans 'Delete' %}">
    </form>

{% endblock %}

templates/project_list.html
{% extends 'base.html' %}

{%load i18n%}
{%load humanize%}
{%block content%}
        <div class="d-flex">

        <h3 class="me-auto">{% trans 'My Projects' %} </h3>
        <div>
            <a href="{% url 'create' %}" class="btn btn-outline-success">
                <i class="bi bi-plus-lg"></i>
                {% trans 'New Project' %}
            </a>

        </div>

    </div>

    <div class="row my-5">
                {% for project in object_list %}
                    <div class="col-md-4">
                        <div class="card mb-3">
                            <div class="card-body" style="    background-color: #617d6a5c; border-radius: 2rem;">
                                <p>
                                    <span class="badge rounded-pill bg-dark">
                                        {{ project.get_statues_display }}
                                    </span>
                                </p>

                                <h3 class="card-title fs-6"> {{ project.title }}</h3>
                                <p class="card-text text-muted small"> {{ project.description }}</p>
                                <div class="d-flex">
                                    <span class="me-auto text-muted small">
                                        <i class="bi bi-clock"></i>
                                        <time datetime="{{ project.created_date }}">
                                            {{ project.create_at|naturaltime }}
                                        </time>
                                    </span>

                                    <a href="{% url 'project_update' project.id %}" class="btn btn-sm btn-outline-dark mx-1">
                                        {% trans 'Edit' %}
                                    </a>

                                      <a href="{% url 'project_delete' project.id %}" class="btn btn-sm btn-outline-danger">
                                          <i class="bi bi-trash"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                {% empty %}
                    <div class="col-md-12" >
                        <div class="h-100 p-5 bg-white border rounded-3 text-center">
                            <p>{% trans 'There Are No Projects To Show' %}</p>
                            <p> <i class="bi bi-emoji-frown fs-1"></i></p>
                            <a href="{% url 'create' %}" class="btn btn-success">
                                <i class="bi bi-plus-lg"></i>
                                {% trans 'New Project' %}
                            </a>
                        </div>
                    </div>
                {% endfor %}


               {% if page_obj.paginator.count > 0 %}
                    <div class="d-flex justify-content-center bd-highlight mb-3">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page_item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{% trans 'Previous' %}</a>
                                    </li>
                                {% else %}
                                    <li class="page_item disabled">
                                        <span class="page-link">{% trans 'Previous' %}</span>
                                    </li>
                                {% endif %}

                                {% if page_obj.has_next %}
                                    <li class="page_item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %}</a>
                                    </li>
                                {% else %}
                                    <li class="page_item disabled">
                                        <span class="page-link">{% trans 'Next' %}</span>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                {% endif %}

    </div>
{% endblock %}

templates/update_project.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <h5>
                    {{ object.title }}
                </h5>
            </li>
        </ol>
    </nav>
    <div class="row">

        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {%for field in form%}
                            <div class="mb-3">{{field}}</div>
                        {%endfor%}

                         <div class="d-flex mt-2">
                                    <span class="me-auto text-muted small">
                                        <i class="bi bi-clock"></i>
                                        <time datetime="{{ project.created_date }}">
                                            {{ progect.create_at }}
                                        </time>
                                    </span>
                         </div>
                        <p></p>
                         <div class="card-footer">
                            <div class="d-grid gap-2 mx-auto">
                                <span></span>
                                <button class="btn btn-success" >
                                    <i class="bi bi-save"></i>
                                    {% trans 'Save' %}
                                </button>

                                 <button class="btn btn-danger" >
                                     <i class="bi bi-trash"></i>
                                    {% trans 'Delete' %}
                                </button>
                            </div>
                         </div>
                     </form>
                </div>
            </div>

        </div>

        <div class="col-md-9">
            {% include 'create_task.html' with project=object %}

    </div>


{% endblock %}


<h3> {% trans 'Update Project' %}</h3>

 <form action="{%url 'project_delete' progect.id %} " method="post">

                {% csrf_token %}
            <input type="submit" value="delete">
 </form>